import { GlobalFonts, createCanvas, loadImage, type Canvas, type Image } from '@napi-rs/canvas';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import {
  computeInitialFit,
  computeLowRes,
  placePersonalizationText,
  renderComposite,
  type CanvasLike,
  type Context2DLike,
  type EditorImage,
} from '../../src/cutout-engine/index.js';
import type { PetNamePosition } from '../../src/types.js';
import casesJson from './cases.json';

/**
 * Golden suite (docs/06 §3): the ported engine must reproduce the STORE's rendering.
 * Baselines under expected/ were generated by gen-baseline.mjs executing the store's own
 * drawCanvas + renderPetName (never this engine). Two independent checks per case:
 *  (a) numeric anchors — hand-computed from the docs/05 formulas, asserted exactly/1e-6;
 *  (b) pixel parity — ≤ 0.1% of pixels may differ by > 2 (of 255) on any channel.
 * Baselines are FROZEN — a change requires a reviewed commit explaining the math change.
 */

interface GoldenCase {
  name: string;
  photo: string;
  natural: { width: number; height: number };
  cutout: string;
  theme: 'light' | 'dark';
  image: Omit<EditorImage, 'id'>;
  lowRes: boolean;
  text?: {
    value: string;
    framePosition?: PetNamePosition;
    customPosition?: PetNamePosition;
    expectedY: number;
  };
}

const CASES = casesJson.cases as GoldenCase[];
const HERE = join(__dirname);

const photos = new Map<string, Image>();
const cutouts = new Map<string, Image>();

beforeAll(async () => {
  GlobalFonts.registerFromPath(join(HERE, 'fixtures/fonts/Mitr-Regular.ttf'), 'Mitr');
  for (const c of CASES) {
    if (!photos.has(c.photo)) {
      photos.set(c.photo, await loadImage(join(HERE, 'fixtures/photos', `${c.photo}.png`)));
    }
    if (!cutouts.has(c.cutout)) {
      cutouts.set(
        c.cutout,
        await loadImage(join(HERE, '../../fixtures/cutouts', `${c.cutout}.png`)),
      );
    }
  }
});

function renderCase(c: GoldenCase): Canvas {
  const canvas = createCanvas(900, 1200);
  renderComposite(canvas as unknown as CanvasLike, {
    images: [{ id: 'p', ...c.image }],
    resolveDrawable: () => photos.get(c.photo),
    cutout: cutouts.get(c.cutout),
    text: c.text
      ? {
          text: c.text.value,
          ...(c.text.framePosition ? { framePosition: c.text.framePosition } : {}),
          ...(c.text.customPosition ? { customPosition: c.text.customPosition } : {}),
          theme: c.theme,
        }
      : null,
  });
  return canvas;
}

/** Pixel diff: fraction of pixels where any RGBA channel differs by more than 2 (of 255). */
async function diffAgainstBaseline(actual: Canvas, name: string): Promise<number> {
  const expectedImg = await loadImage(readFileSync(join(HERE, 'expected', `${name}.png`)));
  const expectedCanvas = createCanvas(900, 1200);
  expectedCanvas.getContext('2d').drawImage(expectedImg, 0, 0);
  const a = actual.getContext('2d').getImageData(0, 0, 900, 1200).data;
  const e = expectedCanvas.getContext('2d').getImageData(0, 0, 900, 1200).data;
  let differing = 0;
  const total = 900 * 1200;
  for (let p = 0; p < total; p++) {
    const i = p * 4;
    if (
      Math.abs(a[i]! - e[i]!) > 2 ||
      Math.abs(a[i + 1]! - e[i + 1]!) > 2 ||
      Math.abs(a[i + 2]! - e[i + 2]!) > 2 ||
      Math.abs(a[i + 3]! - e[i + 3]!) > 2
    ) {
      differing += 1;
    }
  }
  return differing / total;
}

describe('numeric anchors (docs/05 §3 — hand-computed, spec-derived)', () => {
  it.each(CASES.map((c) => [c.name, c] as const))(
    '%s: initial fit matches the hand-computed transform',
    (_name, c) => {
      const fit = computeInitialFit(c.natural.width, c.natural.height);
      // Fit anchors apply to the fitted box; pan/zoom cases share the same base box.
      expect(fit.width).toBeCloseTo(c.image.width, 6);
      expect(fit.height).toBeCloseTo(c.image.height, 6);
      expect(fit.maxScale).toBeCloseTo(c.image.maxScale, 10);
      if (c.name.endsWith('-fit')) {
        expect(fit.x).toBeCloseTo(c.image.x, 6);
        expect(fit.y).toBeCloseTo(c.image.y, 6);
      }
      expect(fit.scale).toBe(1);
      expect(fit.rotation).toBe(0);
    },
  );

  it.each(CASES.map((c) => [c.name, c] as const))('%s: lowRes flag matches', (_name, c) => {
    expect(computeLowRes(c.image, c.natural)).toBe(c.lowRes);
  });

  it('text offsets land at the verbatim 1200-space anchors', () => {
    for (const c of CASES.filter((x) => x.text)) {
      const canvas = createCanvas(900, 1200);
      const ctx = canvas.getContext('2d') as unknown as Context2DLike;
      const placement = placePersonalizationText(ctx, canvas, {
        text: c.text!.value,
        ...(c.text!.framePosition ? { framePosition: c.text!.framePosition } : {}),
        ...(c.text!.customPosition ? { customPosition: c.text!.customPosition } : {}),
        theme: c.theme,
      });
      expect(placement.y, c.name).toBe(c.text!.expectedY);
      expect(placement.x, c.name).toBe(450);
      expect(placement.color, c.name).toBe(c.theme === 'dark' ? 'white' : 'black');
    }
  });
});

describe('pixel parity vs the store-rendered baselines (docs/06 §3 — ≤0.1% over 2/255)', () => {
  it.each(CASES.map((c) => [c.name, c] as const))('%s', async (_name, c) => {
    const ratio = await diffAgainstBaseline(renderCase(c), c.name);
    expect(ratio, `${c.name}: ${(ratio * 100).toFixed(4)}% pixels differ`).toBeLessThanOrEqual(
      0.001,
    );
  });

  it('rendering is deterministic (same case twice → identical pixels)', () => {
    const c = CASES.find((x) => x.text)!;
    const a = renderCase(c).getContext('2d').getImageData(0, 0, 900, 1200).data;
    const b = renderCase(c).getContext('2d').getImageData(0, 0, 900, 1200).data;
    expect(Buffer.from(a.buffer).equals(Buffer.from(b.buffer))).toBe(true);
  });
});
